routes/web.php
<?php

use App\Events\TicketCreated;
use App\Notifications\PostCreatedNotification;
use App\Notifications\RulesChangedNotification;
use App\Podcast;
use App\Ticket;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use NotificationChannels\Telegram\TelegramChannel;

app()->setLocale('fa');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('theme.index');
})->name('home');

Route::namespace('\ElAdmin\UA\Http\Controllers')->prefix('userarea')->middleware([
    'verified'
])->name('userarea.')->group(function(){
   Route::get('/', 'DashboardController@index');
   Route::get('settings', 'DashboardController@settings')->name('settings.index');
   Route::post('settings', 'DashboardController@updateProfile')->name('settings.update');
   Route::get('writers/{writer}', 'WriterController@edit')->name('writers.edit');
   Route::get('writer/request', 'WriterController@create')->name('writers.request');
   Route::resource('writers', 'WriterController')->only(['update', 'store']);
   Route::resource('tickets', 'TicketController');
   Route::resource('books', 'BookController');
});

Route::resource('books', 'BookController');
Route::resource('podcasts', 'PodcastController')->only(['index','show']);
Route::get('contact', 'HomeController@contact');

Route::get('users/{name}', function ($name) {
    return $user = App\User::whereName($name)->firstOrFail();
});

Route::get('sms', 'SmsController@index');

Route::get('notifs', function () {
    $user = User::find(1);
    $notif = new RulesChangedNotification(null, 'database');
    $user->notify($notif->toSms(null));
    // return Notification::send($users, $notif);
});

Route::get('queue', function () {
    // Log::info('hello there !');
    // $podcast = Podcast::find(2);
    // event(new TestEvent($podcast));
    // return $podcast;
    // // // return $podcast;
    // ProcessPodcast::dispatch($podcast)
    //     ->delay(now()->addSeconds(10));
    // Queue::push(function($job){
    //     // Log::info('Hello my queue !');
    //     // $job->delete();
    //     // return 'done !';
    // });
    $user = User::find(23);
    $ticket = Ticket::find(1);
    event(new TicketCreated($user, $ticket));
    return 'yeah !';
    // event(new UserVerified($user));
});

Route::get('telegram-test', function () {
    $podcast = Podcast::find(2);
    $podcast->notify((new PostCreatedNotification($podcast, [TelegramChannel::class]))->delay(now()->addMinute()));
    return 'sent !';
});

Route::get('test', function() {
    $json = '{"pages" : [
        {
            "id": 1,
            "content": [
                {
                    "id": 1
                },
                {
                    "id": 2
                }
            ]
        }
    ]}';
    $json = json_decode($json, true);
    return $json;
    // return response(json_encode($json));
    // return json_encode($json);
    // Auth::loginUsingId(1);
    // $user = auth()->user();
    // $user->unreadNotifications()->update(['read_at' => now()]);
    // // return $user;
    // $book = [];
    // $book['id'] = 678;
    // $notification = new InvoicePaidNotification($book);
    // $user->notify($notification);
});

Auth::routes(['verify' => true]);

Route::prefix('login')->group(function(){
    Route::get('{driver}', 'SocialController@provider')->name('login.driver');
    Route::get('{driver}/validate', 'SocialController@providerRedirect');
});

Route::get('/phpinfo', function () {
    return phpinfo();
});

Route::get('search', function (Request $request) {
    $keyword = $request->keyword ?: '';
    return view('theme.search', compact('keyword'));
})->name('search');

Route::prefix('sitemaps')->name('sitemaps.')->group(function(){
    Route::get('/sitemaps.xml', 'SitemapsController@index');
    Route::get('/sitemap-{sitemap}.xml', 'SitemapsController@show')->name('show');
});

Route::resource('blog', 'BlogController');

Route::get('editor', 'HomeController@editor');

Route::get('/follow/{user}', 'FollowController@follow');

Route::get('/unfollow/{user}', 'FollowController@unfollow');

Route::get('/me', function() {
   $user = User::whereId(auth()->user()->id)->withCount('followings')->firstOrFail();
   $user->load('followings.followable', 'followers.user');
//    return $user;
   return view('theme.sample-profile', compact('user'))->with(['self' => true]);
});

Route::get('/users/{user}', function(User $user) {
//    $user = User::whereId(auth()->user()->id)->withCount('followings')->firstOrFail();
   $user->load('followings.followable', 'followers.user');
   return view('theme.sample-profile', compact('user'))->with(['self' => false]);
});
Route::resource('writers', 'WriterController');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Nicolaslopezj\Searchable\SearchableTrait;

class Post extends Model
{
    use SearchableTrait;
    protected $searchable = [
        'columns' => [
            'title' => 10,
            'summary'=> 5,
        ],
    ];
    public function tags() {
        return $this->belongsToMany(Tag::class);
    }
    public function comments() {
        return $this->morphMany(Comment::class, 'commentable');
    }
    public function likes() {
        return $this->morphMany(Like::class, 'likeable');
    }
    public function categories() {
        return $this->morphMany(Category::class, 'categorable');
    }
    public function bookmarks() {
        return $this->morphMany(Bookmark::class, 'bookmarkable');
    }
    public function seo() {
        return $this->morphOne(SeoInformation::class, 'seoable');
    }
    public function photo() {
        return $this->morphOne(Photo::class, 'photoable');
    }
}

resources/views/theme/components/posts/index.blade.php
@extends('theme.page')

@section('header')
    <title>وبلاگ</title>
    {{-- @component('theme.components.metas', ['seo' => $post->seo, 'target' => $post]) @endcomponent --}}
@endsection

@section('main-content')
    <div class="col-12 mb-4 section posts-page">
        <div class="title-row float-left mb-5">
            <h1 class="title">نوشته ها</h1>
            <span class="underline col-sm-2 offset-sm-5 col-8 offset-2 mt-3">
                <span class="circular-icon"><i class="fas fa-book-open"></i></span>
            </span>
        </div>
        <div class="posts-container col-12 col-xl-10">
            @foreach ($posts as $post)
            <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                <div class="animated flash">
                    @if ($post->photo)
                        <img src="{{ $post->photo->file->thumbnail_path }}" data-src="{{ $post->photo->file->path }}" alt="{{ $post->photo->file->alt }}">
                    @endif
                    <div class="overlay">
                        <div class="float-right badge badge-sm badge-pill">
                            <span>{{ $post->likes_count }}</span>
                            <i class="fas fa-heart text-danger"></i>
                        </div>
                        <div class="float-left badge badge-sm badge-pill">
                            <span>{{ $post->last_views_count }}</span>
                            <i class="fas fa-eye text-dark"></i>
                        </div>
                    </div>
                </div>
                <div class="post-info-container p-2 animated bounce">
                    <div class="p-1">
                        <h3 class="text-dark post-title"><a href="{{ route('blog.show', ['blog' => $post->slug]) }}">{{ $post->title }}</a></h3>
                        <p class="text-secondary post-desc">{{ $post->summary }}</p>
                    </div>
                    <div class="see-section col-12 float-left mb-2">
                        <a href="{{ route('blog.show', ['blog' => $post->slug]) }}" class="btn btn-outline-dark btn-sm pd-3 float-left">مشاهده <i class="fas fa-eye"></i></a>
                    </div>
                </div>
            </div>
            @endforeach
        </div>
        <div class="col-12 pagination-section">
            {{ $posts->links() }}
        </div>
    </div>
@endsection

resources/views/theme/components/posts/show.blade.php
@extends('theme.page')

@section('header')
    <title>{{ $post->title }}</title>
    @component('theme.components.metas', ['seo' => $post->seo, 'target' => $post]) @endcomponent
@endsection

@section('main-content')
    <div class="content-container col-12 col-md-9 col-lg-7">
        <h1>{{ $post->title }}</h1>
        @if ($post->photo)
            <img class="mb-4" src="{{ asset($post->photo->file->thumbnail_path) }}" data-src="{{ asset($post->photo->file->path) }}" alt="{{ $post->photo->file->alt }}">
        @endif
        <span class="date">{{ $post->created_at->diffForHumans() }}</span>
        @guest
            <span>{{ $post->likes_count }} <i class="fa fa-heart text-danger"></i></span>
        @else
            <span>{{ $post->likes_count }} <i class="fa fa-heart text-danger"></i></span>
            <div id="react-like-section"
                data-likes="{{ route('api.userApi.liking', ['target' => 'post', 'targetId' => 'targetId']) }}"
                data-apiKey="{{ auth()->user() ? auth()->user()->api_token : null }}"
            ></div>
        @endguest
        <div class="body-container mt-3">
            {!! $post->body !!}
        </div>
        <h3>سوالات و نظرات</h3>
        <div id="react-comments-section"
            data-comments="{{ route('api.userApi.comments', ['target' => 'post', 'targetId' => $post->id]) }}"
            data-commenting="{{ route('api.userApi.commenting', ['target' => 'post', 'targetId' => $post->id]) }}"
            data-likes="{{ route('api.userApi.liking', ['target' => 'comment', 'targetId' => 'commentId']) }}"
            data-apiKey="{{ auth()->user() ? auth()->user()->api_token : null }}"
        ></div>
    </div>
@endsection

@section('scripts')

@endsection