routes/web.php
<?php

use App\Events\TicketCreated;
use App\Notifications\PostCreatedNotification;
use App\Notifications\RulesChangedNotification;
use App\Podcast;
use App\Ticket;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use NotificationChannels\Telegram\TelegramChannel;

app()->setLocale('fa');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('theme.index');
})->name('home');

Route::namespace('\ElAdmin\UA\Http\Controllers')->prefix('userarea')->middleware([
    'verified'
])->name('userarea.')->group(function(){
   Route::get('/', 'DashboardController@index');
   Route::get('settings', 'DashboardController@settings')->name('settings.index');
   Route::post('settings', 'DashboardController@updateProfile')->name('settings.update');
   Route::get('writers/{writer}', 'WriterController@edit')->name('writers.edit');
   Route::get('writer/request', 'WriterController@create')->name('writers.request');
   Route::resource('writers', 'WriterController')->only(['update', 'store']);
   Route::resource('tickets', 'TicketController');
   Route::resource('books', 'BookController');
});

Route::resource('books', 'BookController');
Route::resource('podcasts', 'PodcastController')->only(['index','show']);
Route::get('contact', 'HomeController@contact');

Route::get('users/{name}', function ($name) {
    return $user = App\User::whereName($name)->firstOrFail();
});

Route::get('sms', 'SmsController@index');

Route::get('notifs', function () {
    $user = User::find(1);
    $notif = new RulesChangedNotification(null, 'database');
    $user->notify($notif->toSms(null));
    // return Notification::send($users, $notif);
});

Route::get('queue', function () {
    // Log::info('hello there !');
    // $podcast = Podcast::find(2);
    // event(new TestEvent($podcast));
    // return $podcast;
    // // // return $podcast;
    // ProcessPodcast::dispatch($podcast)
    //     ->delay(now()->addSeconds(10));
    // Queue::push(function($job){
    //     // Log::info('Hello my queue !');
    //     // $job->delete();
    //     // return 'done !';
    // });
    $user = User::find(23);
    $ticket = Ticket::find(1);
    event(new TicketCreated($user, $ticket));
    return 'yeah !';
    // event(new UserVerified($user));
});

Route::get('telegram-test', function () {
    $podcast = Podcast::find(2);
    $podcast->notify((new PostCreatedNotification($podcast, [TelegramChannel::class]))->delay(now()->addMinute()));
    return 'sent !';
});

Route::get('test', function() {
    $json = '{"pages" : [
        {
            "id": 1,
            "content": [
                {
                    "id": 1
                },
                {
                    "id": 2
                }
            ]
        }
    ]}';
    $json = json_decode($json, true);
    return $json;
    // return response(json_encode($json));
    // return json_encode($json);
    // Auth::loginUsingId(1);
    // $user = auth()->user();
    // $user->unreadNotifications()->update(['read_at' => now()]);
    // // return $user;
    // $book = [];
    // $book['id'] = 678;
    // $notification = new InvoicePaidNotification($book);
    // $user->notify($notification);
});

Auth::routes(['verify' => true]);

Route::prefix('login')->group(function(){
    Route::get('{driver}', 'SocialController@provider')->name('login.driver');
    Route::get('{driver}/validate', 'SocialController@providerRedirect');
});

Route::get('/phpinfo', function () {
    return phpinfo();
});

Route::get('search', function (Request $request) {
    $keyword = $request->keyword ?: '';
    return view('theme.search', compact('keyword'));
})->name('search');

Route::prefix('sitemaps')->name('sitemaps.')->group(function(){
    Route::get('/sitemaps.xml', 'SitemapsController@index');
    Route::get('/sitemap-{sitemap}.xml', 'SitemapsController@show')->name('show');
});

Route::resource('blog', 'BlogController');

Route::get('editor', 'HomeController@editor');

Route::get('/follow/{user}', 'FollowController@follow');

Route::get('/unfollow/{user}', 'FollowController@unfollow');

Route::get('/me', function() {
   $user = User::whereId(auth()->user()->id)->withCount('followings')->firstOrFail();
   $user->load('followings.followable', 'followers.user');
//    return $user;
   return view('theme.sample-profile', compact('user'))->with(['self' => true]);
});

Route::get('/users/{user}', function(User $user) {
//    $user = User::whereId(auth()->user()->id)->withCount('followings')->firstOrFail();
   $user->load('followings.followable', 'followers.user');
   return view('theme.sample-profile', compact('user'))->with(['self' => false]);
});
Route::resource('writers', 'WriterController');

resources/views/theme/components/footer.blade.php
<footer>
    <div class="col-md-3 col-12">
        <h6 class="footer-title">ال ناول</h6>
        <p>این جمله ای که داری میخونی قراره بعدا بشه درباره ما ولی خب فعلا به دلیل کمبود وقت مجبوریم جاش همین کلمات رو جایگزین کنیم.
            خلاصه فعلا با همین حال کنید تا یک چیزی واسه جایگزین پیدا کنیم
        </p>
    </div>
    <div class="col-md-3 col-12">
        <h6 class="footer-title">صفحات</h6>
        <ul class="col-md-6 float-right">
            <li><a href="/">خانه</a></li>
            <li><a href="/novels">رمان ها</a></li>
            <li><a href="/generes">ژانرها</a></li>
        </ul>
        <ul class="col-md-6 float-right">
            <li><a href="/podcasts">پادکست ها</a></li>
            <li><a href="/profile">حساب کاربری</a></li>
        </ul>
    </div>
    <div class="col-md-3 col-12">
        <h6 class="footer-title">ارتباط با ما</h6>
        <ul class="non-dots">
            <li><i class="fas fa-building ml-3"></i>دفتر مرکزی : مشهد ، سه راه ادبیات ، کوچه کتاب ، پلاک 22</li>
            <li><a class="phone" href="mailto:info@elnovel.net"><i class="fas fa-envelope-open"></i>info(@)elnovel(.)net</a></li>
            <li><a class="phone" href="tel:+989150013422"><i class="fas fa-phone"></i>0915 001 34 22</a></li>
            <li><a class="phone" href="tel:+989015074027"><i class="fas fa-phone"></i>0901 507 40 27</a></li>
            <li><a class="phone" href="tel:+985138859010"><i class="fas fa-tty"></i>051-38 85 90 10</a></li>
        </ul>
    </div>
    <div class="col-md-3 col-12">
        <h6 class="footer-title">شبکه های اجتماعی</h6>
        <ul class="social-media">
            <li><a href="https://instagram.com/elnovelofficial"><i class="fab fa-instagram"></i></a></li>
            <li><a href="https://t.me/elnovel"><i class="fas fa-paper-plane"></i></a></li>
            <li><a href="https://www.youtube.com/channel/UCDpTgLgveZqx7le4PYQfHfA"><i class="fab fa-youtube"></i></a></li>
            <li><a href="https://twitter.com/ElnovelOfficial"><i class="fab fa-twitter"></i></a></li>
            {{-- <li><a href="#social-media"><i class="fab fa-facebook-f"></i></a></li> --}}
            <li><a href="https://api.whatsapp.com/send?phone=989150013422&text=%D8%B3%D9%84%D8%A7%D9%85"><i class="fab fa-whatsapp"></i></a></li>
            <li><a href="https://www.linkedin.com/company/elnovel/"><i class="fab fa-linkedin"></i></a></li>
			<li><a href="https://soundcloud.com/elnovel"><i class="fab fa-soundcloud"></i></a></li>
        </ul>
    </div>
    <div class="col-12 pt-3 bottom-footer">
        <p class="col-12 text-center copyright">COPYRIGHT 2020 &COPY; ELNOVEL Co.<br>ALL RIGHTS RESERVED</p>
    </div>
</footer>

resources/views/theme/components/header.blade.php
@include('theme.components.search')
<header>
    @include('theme.components.menu')
    @include('theme.components.slider')
</header>

resources/views/theme/components/menu.blade.php
<nav class="menu">
    <div class="logo">
        <a href="{{ route('home') }}"><img src="{{ route('home') }}/images/logo.png" alt=""></a>
    </div>
    <ul>
        <li><a href="{{ asset('/') }}">خونه</a></li>
        <li><a href="{{ asset('/novels') }}">رمان ها</a></li>
        <li><a href="{{ asset('/writers') }}">داستان نویس ها</a></li>
        <li><a href="{{ asset('/podcasts') }}">پادکست ها</a></li>
        <li><a href="{{ route('blog.index') }}">وبلاگ</a></li>
        <li><a href="{{ asset('/contact') }}">تماس با ما</a></li>
        <li><a href="{{ route('search') }}">جستجو</a></li>
    </ul>
    <div class="last col-sm-6 col-12">
    <div class="btn btn-dark float-left d-sm-none d-block" id="menu-opener">
        <i class="fas fa-2x fa-bars"></i>
    </div>
    @guest
    <p class="float-left text-center col-lg-12 col-8 white h-100">
        <span id="search-icon" class="search-icon"><i class="fas fa-search"></i></span>
        <span class="search-icon">
            <a class="mt-0" href="{{ route('register') }}"><i class="fas fa-user"></i> عضویت</a>
            <a class="mt-0" href="{{ route('login') }}"><i class="fas fa-lock"></i> ورود</a>
        </span>
    </p>
    @else
        <p class="float-left text-center col-lg-12 col-8 white h-100">
            <a class="float-left text-center search-icon d-sm-block d-none" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
            @lang('auth.logout') <i class="fas fa-sign-out-alt"></i>
            </a>
            <span id="search-icon" class="search-icon"><i class="fas fa-search"></i></span>
            <a href="{{ route('userarea.') }}" class="search-icon">{{ ucfirst(auth()->user()->name) }} <i class="fas fa-user"></i></a>
        </p>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
        </form>
    @endguest
    </div>
</nav>

resources/views/theme/components/metas.blade.php
@if ($seo)
    <meta name="description" content="{{ $seo->description }}">
    <meta name="keywords" content="{{ organize_keywords_for_seo($seo->keywords) }}">
    <meta name="robots" cotnent="{{ $seo->robots }}">
    <meta name="copyright" content="{{ config('app.name') }}">
    <meta name="author" content="{{ config('app.author') }}">
    <meta name="application-name" content="{{ config('app.name') }}">
    <meta name="shortcut icon" type="image/x-icon" href="">
    <link rel="canonical" href="{{ config('app.url') }}">
    <meta property="og:site_name" content="{{ config('app.name') }}" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="{{ $target->title }}" />
@if($target->photo)
    <meta property="og:image" content="{{ asset($target->photo->file->path) }}" />
@endif
    <meta property="og:url" content="{{ url()->current() }}" />
@if($target->description)
    <meta property="og:description" content="{{ $target->description }}" />
@endif
    <meta name="twitter:title" content="{{ $target->title }}">
@if($target->description)
    <meta name="twitter:description" content="{{ $target->description }}">
@endif
@if($target->photo)
    <meta name="twitter:image" content="{{ asset($target->photo->file->path) }}">
@endif
    <meta name="twitter:site" content="@USERNAME">
    <meta name="twitter:creator" content="@USERNAME">
@endif
{{-- <link rel="alternate" type="application/rss+xml" href="{{ asset('/events.rss') }}" title="Upcoming Events"> --}}

resources/views/theme/components/search.blade.php
<div
    id="react-search" 
    class="search-section col-12"
    search={{ route('api.platform.search', ['keyword' => 'keyword']) }}
    searchPro={{ route('api.platform.search.pro', ['keyword' => 'keyword']) }}
></div>

resources/views/theme/components/slider.blade.php
<div class="swiper-container" id="slider">
    <!-- Additional required wrapper -->
    <div class="swiper-wrapper">
        <!-- Slides -->
        <div class="swiper-slide"><img src="{{ asset('images/slide.jpg') }}" alt=""></div>
        <div class="swiper-slide"><img src="{{ asset('images/slider-1.jpg') }}" alt=""></div>
        <div class="swiper-slide"><img src="{{ asset('images/slider-2.jpg') }}" alt=""></div>
        <div class="swiper-slide"><img src="{{ asset('images/slider-3.jpg') }}" alt=""></div>
    </div>
    <!-- If we need pagination -->
    <div class="swiper-pagination"></div>
    <!-- If we need navigation buttons -->
    <div class="swiper-button-prev"><i class="fas fa-4x fa-angle-left"></i></div>
    <div class="swiper-button-next"><i class="fas fa-4x fa-angle-right"></i></div>
</div>